"""add knowledge_chunks table for RAG

Revision ID: 64768fc170aa
Revises: 6f0df771aebf
Create Date: 2026-08-07 16:41:48.093569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '64768fc170aa'
down_revision: Union[str, Sequence[str], None] = '6f0df771aebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector ships as a Postgres extension - the pgvector/pgvector:pg16 image has
    # it available but not enabled by default, so it must be turned on before any
    # table can use the `vector` column type. Not something autogenerate detects
    # on its own (it only diffs SQLAlchemy metadata, not extensions).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('FOOTBALL', 'HYROX', 'BODYBUILDING', 'INJURY_PREVENTION', name='knowledge_domain'), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # HNSW index for approximate nearest-neighbor cosine search - not something
    # autogenerate writes either, since it's a pgvector-specific index type.
    # vector_cosine_ops matches the cosine-distance operator (<=>) the retriever uses.
    op.execute(
        "CREATE INDEX knowledge_chunks_embedding_hnsw_idx "
        "ON knowledge_chunks USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS knowledge_chunks_embedding_hnsw_idx")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
    # Deliberately not dropping the `vector` extension itself - other tables/future
    # migrations may depend on it, and DROP EXTENSION would cascade to them.
