"""create initial fitness tables

Revision ID: 6f0df771aebf
Revises: 
Create Date: 2026-08-06 23:50:20.594988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0df771aebf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('goals', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sports_played', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('training_preferences', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_type', sa.Enum('STRENGTH', 'CARDIO', 'FOOTBALL', 'HYROX', 'RUNNING', 'MOBILITY', 'OTHER', name='exercise_type'), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pace', sa.String(length=20), nullable=True),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('football_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('match_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.String(length=20), nullable=True),
    sa.Column('performance_notes', sa.Text(), nullable=True),
    sa.Column('injuries_flagged', sa.Boolean(), nullable=False),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id')
    )
    op.create_table('hyrox_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('ski_erg_seconds', sa.Integer(), nullable=True),
    sa.Column('sled_push_seconds', sa.Integer(), nullable=True),
    sa.Column('sled_pull_seconds', sa.Integer(), nullable=True),
    sa.Column('burpees_reps', sa.Integer(), nullable=True),
    sa.Column('burpees_seconds', sa.Integer(), nullable=True),
    sa.Column('rowing_seconds', sa.Integer(), nullable=True),
    sa.Column('farmers_carry_seconds', sa.Integer(), nullable=True),
    sa.Column('lunges_reps', sa.Integer(), nullable=True),
    sa.Column('wall_balls_reps', sa.Integer(), nullable=True),
    sa.Column('total_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id')
    )
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_workout_id', sa.Integer(), nullable=True),
    sa.Column('injury_type', sa.String(length=100), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('severity', sa.Enum('MILD', 'MODERATE', 'SEVERE', name='injury_severity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RECOVERING', 'RECOVERED', name='injury_status'), nullable=False),
    sa.Column('recovery_exercises', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_workout_id'], ['workouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('running_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pace_per_km', sa.String(length=20), nullable=True),
    sa.Column('vo2max_estimate', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('running_sessions')
    op.drop_table('injuries')
    op.drop_table('hyrox_sessions')
    op.drop_table('football_sessions')
    op.drop_table('workouts')
    op.drop_table('users')
    # ### end Alembic commands ###
